# Generated by Django 3.0.7 on 2020-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(max_length=5),
        ),
    ]
