# Generated by Django 3.0.7 on 2020-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0002_auto_20200625_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=20)),
                ('usercontact', models.IntegerField(max_length=10)),
                ('useraddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
