# Generated by Django 3.0.7 on 2020-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0003_auto_20200625_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='usercontact',
            field=models.CharField(max_length=10),
        ),
    ]
