# Generated by Django 3.0.7 on 2020-06-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0004_auto_20200625_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetail',
            new_name='Userdetails',
        ),
    ]
